// Generated by gencpp from file symbolic_msgs/perception.msg
// DO NOT EDIT!


#ifndef SYMBOLIC_MSGS_MESSAGE_PERCEPTION_H
#define SYMBOLIC_MSGS_MESSAGE_PERCEPTION_H

#include <ros/service_traits.h>


#include <symbolic_msgs/perceptionRequest.h>
#include <symbolic_msgs/perceptionResponse.h>


namespace symbolic_msgs
{

struct perception
{

typedef perceptionRequest Request;
typedef perceptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct perception
} // namespace symbolic_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::symbolic_msgs::perception > {
  static const char* value()
  {
    return "66a96c4350836d51ca0d6a2c28ae7f73";
  }

  static const char* value(const ::symbolic_msgs::perception&) { return value(); }
};

template<>
struct DataType< ::symbolic_msgs::perception > {
  static const char* value()
  {
    return "symbolic_msgs/perception";
  }

  static const char* value(const ::symbolic_msgs::perception&) { return value(); }
};


// service_traits::MD5Sum< ::symbolic_msgs::perceptionRequest> should match
// service_traits::MD5Sum< ::symbolic_msgs::perception >
template<>
struct MD5Sum< ::symbolic_msgs::perceptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::symbolic_msgs::perception >::value();
  }
  static const char* value(const ::symbolic_msgs::perceptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::symbolic_msgs::perceptionRequest> should match
// service_traits::DataType< ::symbolic_msgs::perception >
template<>
struct DataType< ::symbolic_msgs::perceptionRequest>
{
  static const char* value()
  {
    return DataType< ::symbolic_msgs::perception >::value();
  }
  static const char* value(const ::symbolic_msgs::perceptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::symbolic_msgs::perceptionResponse> should match
// service_traits::MD5Sum< ::symbolic_msgs::perception >
template<>
struct MD5Sum< ::symbolic_msgs::perceptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::symbolic_msgs::perception >::value();
  }
  static const char* value(const ::symbolic_msgs::perceptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::symbolic_msgs::perceptionResponse> should match
// service_traits::DataType< ::symbolic_msgs::perception >
template<>
struct DataType< ::symbolic_msgs::perceptionResponse>
{
  static const char* value()
  {
    return DataType< ::symbolic_msgs::perception >::value();
  }
  static const char* value(const ::symbolic_msgs::perceptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYMBOLIC_MSGS_MESSAGE_PERCEPTION_H
