// Generated by gencpp from file symbolic_msgs/perceptionResponse.msg
// DO NOT EDIT!


#ifndef SYMBOLIC_MSGS_MESSAGE_PERCEPTIONRESPONSE_H
#define SYMBOLIC_MSGS_MESSAGE_PERCEPTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision_msgs/Detection2DArray.h>
#include <std_msgs/Int16MultiArray.h>
#include <vision_msgs/Detection3DArray.h>
#include <geometry_msgs/PoseArray.h>
#include <vision_msgs/BoundingBox3D.h>
#include <vision_msgs/BoundingBox3D.h>

namespace symbolic_msgs
{
template <class ContainerAllocator>
struct perceptionResponse_
{
  typedef perceptionResponse_<ContainerAllocator> Type;

  perceptionResponse_()
    : success(false)
    , det_2d()
    , instance_id()
    , det_3d()
    , grasp_pose()
    , table_pose()
    , shelf_pose()  {
    }
  perceptionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , det_2d(_alloc)
    , instance_id(_alloc)
    , det_3d(_alloc)
    , grasp_pose(_alloc)
    , table_pose(_alloc)
    , shelf_pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::vision_msgs::Detection2DArray_<ContainerAllocator>  _det_2d_type;
  _det_2d_type det_2d;

   typedef  ::std_msgs::Int16MultiArray_<ContainerAllocator>  _instance_id_type;
  _instance_id_type instance_id;

   typedef  ::vision_msgs::Detection3DArray_<ContainerAllocator>  _det_3d_type;
  _det_3d_type det_3d;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _grasp_pose_type;
  _grasp_pose_type grasp_pose;

   typedef  ::vision_msgs::BoundingBox3D_<ContainerAllocator>  _table_pose_type;
  _table_pose_type table_pose;

   typedef  ::vision_msgs::BoundingBox3D_<ContainerAllocator>  _shelf_pose_type;
  _shelf_pose_type shelf_pose;





  typedef boost::shared_ptr< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct perceptionResponse_

typedef ::symbolic_msgs::perceptionResponse_<std::allocator<void> > perceptionResponse;

typedef boost::shared_ptr< ::symbolic_msgs::perceptionResponse > perceptionResponsePtr;
typedef boost::shared_ptr< ::symbolic_msgs::perceptionResponse const> perceptionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::symbolic_msgs::perceptionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::symbolic_msgs::perceptionResponse_<ContainerAllocator1> & lhs, const ::symbolic_msgs::perceptionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.det_2d == rhs.det_2d &&
    lhs.instance_id == rhs.instance_id &&
    lhs.det_3d == rhs.det_3d &&
    lhs.grasp_pose == rhs.grasp_pose &&
    lhs.table_pose == rhs.table_pose &&
    lhs.shelf_pose == rhs.shelf_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::symbolic_msgs::perceptionResponse_<ContainerAllocator1> & lhs, const ::symbolic_msgs::perceptionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace symbolic_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0b9e0274823afa5f617b0cb4bacf180";
  }

  static const char* value(const ::symbolic_msgs::perceptionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0b9e0274823afa5ULL;
  static const uint64_t static_value2 = 0xf617b0cb4bacf180ULL;
};

template<class ContainerAllocator>
struct DataType< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "symbolic_msgs/perceptionResponse";
  }

  static const char* value(const ::symbolic_msgs::perceptionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# rosponse\n"
"bool success\n"
"vision_msgs/Detection2DArray det_2d\n"
"std_msgs/Int16MultiArray instance_id\n"
"vision_msgs/Detection3DArray det_3d\n"
"geometry_msgs/PoseArray grasp_pose\n"
"vision_msgs/BoundingBox3D table_pose\n"
"vision_msgs/BoundingBox3D shelf_pose\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/Detection2DArray\n"
"# A list of 2D detections, for a multi-object 2D detector.\n"
"\n"
"Header header\n"
"\n"
"# A list of the detected proposals. A multi-proposal detector might generate\n"
"#   this list with many candidate detections generated from a single input.\n"
"Detection2D[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/Detection2D\n"
"# Defines a 2D detection result.\n"
"#\n"
"# This is similar to a 2D classification, but includes position information,\n"
"#   allowing a classification result for a specific crop or image point to\n"
"#   to be located in the larger image.\n"
"\n"
"Header header\n"
"\n"
"# Class probabilities\n"
"ObjectHypothesisWithPose[] results\n"
"\n"
"# 2D bounding box surrounding the object.\n"
"BoundingBox2D bbox\n"
"\n"
"# The 2D data that generated these results (i.e. region proposal cropped out of\n"
"#   the image). Not required for all use cases, so it may be empty.\n"
"sensor_msgs/Image source_img\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/ObjectHypothesisWithPose\n"
"# An object hypothesis that contains position information.\n"
"\n"
"# The unique numeric ID of object detected. To get additional information about\n"
"#   this ID, such as its human-readable name, listeners should perform a lookup\n"
"#   in a metadata database. See vision_msgs/VisionInfo.msg for more detail.\n"
"int64 id\n"
"\n"
"# The probability or confidence value of the detected object. By convention,\n"
"#   this value should lie in the range [0-1].\n"
"float64 score\n"
"\n"
"# The 6D pose of the object hypothesis. This pose should be\n"
"#   defined as the pose of some fixed reference point on the object, such a\n"
"#   the geometric center of the bounding box or the center of mass of the\n"
"#   object.\n"
"# Note that this pose is not stamped; frame information can be defined by\n"
"#   parent messages.\n"
"# Also note that different classes predicted for the same input data may have\n"
"#   different predicted 6D poses.\n"
"geometry_msgs/PoseWithCovariance pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/BoundingBox2D\n"
"# A 2D bounding box that can be rotated about its center.\n"
"# All dimensions are in pixels, but represented using floating-point\n"
"#   values to allow sub-pixel precision. If an exact pixel crop is required\n"
"#   for a rotated bounding box, it can be calculated using Bresenham's line\n"
"#   algorithm.\n"
"\n"
"# The 2D position (in pixels) and orientation of the bounding box center.\n"
"geometry_msgs/Pose2D center\n"
"\n"
"# The size (in pixels) of the bounding box surrounding the object relative\n"
"#   to the pose of its center.\n"
"float64 size_x\n"
"float64 size_y\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int16[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: vision_msgs/Detection3DArray\n"
"# A list of 3D detections, for a multi-object 3D detector.\n"
"\n"
"Header header\n"
"\n"
"# A list of the detected proposals. A multi-proposal detector might generate\n"
"#   this list with many candidate detections generated from a single input.\n"
"Detection3D[] detections\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/Detection3D\n"
"# Defines a 3D detection result.\n"
"#\n"
"# This extends a basic 3D classification by including position information,\n"
"#   allowing a classification result for a specific position in an image to\n"
"#   to be located in the larger image.\n"
"\n"
"Header header\n"
"\n"
"# Class probabilities. Does not have to include hypotheses for all possible\n"
"#   object ids, the scores for any ids not listed are assumed to be 0.\n"
"ObjectHypothesisWithPose[] results\n"
"\n"
"# 3D bounding box surrounding the object.\n"
"BoundingBox3D bbox\n"
"\n"
"# The 3D data that generated these results (i.e. region proposal cropped out of\n"
"#   the image). This information is not required for all detectors, so it may\n"
"#   be empty.\n"
"sensor_msgs/PointCloud2 source_cloud\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/BoundingBox3D\n"
"# A 3D bounding box that can be positioned and rotated about its center (6 DOF)\n"
"# Dimensions of this box are in meters, and as such, it may be migrated to\n"
"#   another package, such as geometry_msgs, in the future.\n"
"\n"
"# The 3D position and orientation of the bounding box center\n"
"geometry_msgs/Pose center\n"
"\n"
"# The size of the bounding box, in meters, surrounding the object's center\n"
"#   pose.\n"
"geometry_msgs/Vector3 size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
;
  }

  static const char* value(const ::symbolic_msgs::perceptionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.det_2d);
      stream.next(m.instance_id);
      stream.next(m.det_3d);
      stream.next(m.grasp_pose);
      stream.next(m.table_pose);
      stream.next(m.shelf_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct perceptionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::symbolic_msgs::perceptionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::symbolic_msgs::perceptionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "det_2d: ";
    s << std::endl;
    Printer< ::vision_msgs::Detection2DArray_<ContainerAllocator> >::stream(s, indent + "  ", v.det_2d);
    s << indent << "instance_id: ";
    s << std::endl;
    Printer< ::std_msgs::Int16MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.instance_id);
    s << indent << "det_3d: ";
    s << std::endl;
    Printer< ::vision_msgs::Detection3DArray_<ContainerAllocator> >::stream(s, indent + "  ", v.det_3d);
    s << indent << "grasp_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_pose);
    s << indent << "table_pose: ";
    s << std::endl;
    Printer< ::vision_msgs::BoundingBox3D_<ContainerAllocator> >::stream(s, indent + "  ", v.table_pose);
    s << indent << "shelf_pose: ";
    s << std::endl;
    Printer< ::vision_msgs::BoundingBox3D_<ContainerAllocator> >::stream(s, indent + "  ", v.shelf_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYMBOLIC_MSGS_MESSAGE_PERCEPTIONRESPONSE_H
