// Generated by gencpp from file service_pkg/service_srv.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_SERVICE_SRV_H
#define SERVICE_PKG_MESSAGE_SERVICE_SRV_H

#include <ros/service_traits.h>


#include <service_pkg/service_srvRequest.h>
#include <service_pkg/service_srvResponse.h>


namespace service_pkg
{

struct service_srv
{

typedef service_srvRequest Request;
typedef service_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service_srv
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::service_srv > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_pkg::service_srv&) { return value(); }
};

template<>
struct DataType< ::service_pkg::service_srv > {
  static const char* value()
  {
    return "service_pkg/service_srv";
  }

  static const char* value(const ::service_pkg::service_srv&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::service_srvRequest> should match
// service_traits::MD5Sum< ::service_pkg::service_srv >
template<>
struct MD5Sum< ::service_pkg::service_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::service_srv >::value();
  }
  static const char* value(const ::service_pkg::service_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::service_srvRequest> should match
// service_traits::DataType< ::service_pkg::service_srv >
template<>
struct DataType< ::service_pkg::service_srvRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::service_srv >::value();
  }
  static const char* value(const ::service_pkg::service_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::service_srvResponse> should match
// service_traits::MD5Sum< ::service_pkg::service_srv >
template<>
struct MD5Sum< ::service_pkg::service_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::service_srv >::value();
  }
  static const char* value(const ::service_pkg::service_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::service_srvResponse> should match
// service_traits::DataType< ::service_pkg::service_srv >
template<>
struct DataType< ::service_pkg::service_srvResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::service_srv >::value();
  }
  static const char* value(const ::service_pkg::service_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_SERVICE_SRV_H
