// Generated by gencpp from file service_pkg/service_srvResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_SERVICE_SRVRESPONSE_H
#define SERVICE_PKG_MESSAGE_SERVICE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct service_srvResponse_
{
  typedef service_srvResponse_<ContainerAllocator> Type;

  service_srvResponse_()
    : sum(0)  {
    }
  service_srvResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::service_pkg::service_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::service_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct service_srvResponse_

typedef ::service_pkg::service_srvResponse_<std::allocator<void> > service_srvResponse;

typedef boost::shared_ptr< ::service_pkg::service_srvResponse > service_srvResponsePtr;
typedef boost::shared_ptr< ::service_pkg::service_srvResponse const> service_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::service_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::service_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::service_srvResponse_<ContainerAllocator1> & lhs, const ::service_pkg::service_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::service_srvResponse_<ContainerAllocator1> & lhs, const ::service_pkg::service_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::service_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::service_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::service_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::service_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::service_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::service_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::service_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::service_pkg::service_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::service_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/service_srvResponse";
  }

  static const char* value(const ::service_pkg::service_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::service_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 sum\n"
"\n"
;
  }

  static const char* value(const ::service_pkg::service_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::service_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::service_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::service_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_SERVICE_SRVRESPONSE_H
