// Generated by gencpp from file service_pkg/service_srvRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_SERVICE_SRVREQUEST_H
#define SERVICE_PKG_MESSAGE_SERVICE_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct service_srvRequest_
{
  typedef service_srvRequest_<ContainerAllocator> Type;

  service_srvRequest_()
    : a(0)
    , b(0)  {
    }
  service_srvRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::service_pkg::service_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::service_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct service_srvRequest_

typedef ::service_pkg::service_srvRequest_<std::allocator<void> > service_srvRequest;

typedef boost::shared_ptr< ::service_pkg::service_srvRequest > service_srvRequestPtr;
typedef boost::shared_ptr< ::service_pkg::service_srvRequest const> service_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::service_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::service_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::service_srvRequest_<ContainerAllocator1> & lhs, const ::service_pkg::service_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::service_srvRequest_<ContainerAllocator1> & lhs, const ::service_pkg::service_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::service_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::service_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::service_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::service_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::service_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::service_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::service_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::service_pkg::service_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::service_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/service_srvRequest";
  }

  static const char* value(const ::service_pkg::service_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::service_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 a\n"
"int64 b\n"
"\n"
;
  }

  static const char* value(const ::service_pkg::service_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::service_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::service_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::service_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_SERVICE_SRVREQUEST_H
