// Generated by gencpp from file njh_panda_moveit_pkg/test_moveit_serviceRequest.msg
// DO NOT EDIT!


#ifndef NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICEREQUEST_H
#define NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace njh_panda_moveit_pkg
{
template <class ContainerAllocator>
struct test_moveit_serviceRequest_
{
  typedef test_moveit_serviceRequest_<ContainerAllocator> Type;

  test_moveit_serviceRequest_()
    : a(0)
    , b(0)  {
    }
  test_moveit_serviceRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_moveit_serviceRequest_

typedef ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<std::allocator<void> > test_moveit_serviceRequest;

typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceRequest > test_moveit_serviceRequestPtr;
typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceRequest const> test_moveit_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator1> & lhs, const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator1> & lhs, const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace njh_panda_moveit_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "njh_panda_moveit_pkg/test_moveit_serviceRequest";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 a\n"
"int64 b\n"
"\n"
;
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_moveit_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::njh_panda_moveit_pkg::test_moveit_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICEREQUEST_H
