// Generated by gencpp from file njh_panda_moveit_pkg/test_moveit_serviceResponse.msg
// DO NOT EDIT!


#ifndef NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICERESPONSE_H
#define NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace njh_panda_moveit_pkg
{
template <class ContainerAllocator>
struct test_moveit_serviceResponse_
{
  typedef test_moveit_serviceResponse_<ContainerAllocator> Type;

  test_moveit_serviceResponse_()
    : sum(0)  {
    }
  test_moveit_serviceResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct test_moveit_serviceResponse_

typedef ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<std::allocator<void> > test_moveit_serviceResponse;

typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceResponse > test_moveit_serviceResponsePtr;
typedef boost::shared_ptr< ::njh_panda_moveit_pkg::test_moveit_serviceResponse const> test_moveit_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator1> & lhs, const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator1> & lhs, const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace njh_panda_moveit_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "njh_panda_moveit_pkg/test_moveit_serviceResponse";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 sum\n"
"\n"
"\n"
;
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_moveit_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::njh_panda_moveit_pkg::test_moveit_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICERESPONSE_H
