// Generated by gencpp from file njh_panda_moveit_pkg/test_moveit_service.msg
// DO NOT EDIT!


#ifndef NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICE_H
#define NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICE_H

#include <ros/service_traits.h>


#include <njh_panda_moveit_pkg/test_moveit_serviceRequest.h>
#include <njh_panda_moveit_pkg/test_moveit_serviceResponse.h>


namespace njh_panda_moveit_pkg
{

struct test_moveit_service
{

typedef test_moveit_serviceRequest Request;
typedef test_moveit_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_moveit_service
} // namespace njh_panda_moveit_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::njh_panda_moveit_pkg::test_moveit_service > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_service&) { return value(); }
};

template<>
struct DataType< ::njh_panda_moveit_pkg::test_moveit_service > {
  static const char* value()
  {
    return "njh_panda_moveit_pkg/test_moveit_service";
  }

  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_service&) { return value(); }
};


// service_traits::MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceRequest> should match
// service_traits::MD5Sum< ::njh_panda_moveit_pkg::test_moveit_service >
template<>
struct MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::njh_panda_moveit_pkg::test_moveit_service >::value();
  }
  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::njh_panda_moveit_pkg::test_moveit_serviceRequest> should match
// service_traits::DataType< ::njh_panda_moveit_pkg::test_moveit_service >
template<>
struct DataType< ::njh_panda_moveit_pkg::test_moveit_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::njh_panda_moveit_pkg::test_moveit_service >::value();
  }
  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceResponse> should match
// service_traits::MD5Sum< ::njh_panda_moveit_pkg::test_moveit_service >
template<>
struct MD5Sum< ::njh_panda_moveit_pkg::test_moveit_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::njh_panda_moveit_pkg::test_moveit_service >::value();
  }
  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::njh_panda_moveit_pkg::test_moveit_serviceResponse> should match
// service_traits::DataType< ::njh_panda_moveit_pkg::test_moveit_service >
template<>
struct DataType< ::njh_panda_moveit_pkg::test_moveit_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::njh_panda_moveit_pkg::test_moveit_service >::value();
  }
  static const char* value(const ::njh_panda_moveit_pkg::test_moveit_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NJH_PANDA_MOVEIT_PKG_MESSAGE_TEST_MOVEIT_SERVICE_H
